# Generated by Django 4.2.3 on 2023-07-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='apellido',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='persona',
            name='edad',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='persona',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
