# Generated by Django 4.2.3 on 2023-07-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_persona_apellido_persona_edad_persona_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(default='Sin Marca', max_length=20)),
                ('patente', models.CharField(default='Sin Patente', max_length=6)),
            ],
        ),
    ]
